

services:
  web:
    build: .
    command: gunicorn magical.wsgi:application --bind 0.0.0.0:8000 --workers=3
    volumes:
      - ./staticfiles:/app/staticfiles
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env  # Load environment variables from .env file

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
